export { newObject }

function newObject () {
  let obj = [
    { text: 'absentees', value: '1', platform: 'reach' },
    { text: 'browser', value: '2', platform: 'reach' },
    { text: 'businesses', value: '3', platform: 'reach' },
    { text: 'contacts', value: '4', platform: 'reach' },
    { text: 'custom-content', value: '5', platform: 'reach' },
    { text: 'events', value: '6', platform: 'reach' },
    { text: 'feeds', value: '7', platform: 'reach' },
    { text: 'galleries', value: '8', platform: 'reach' },
    { text: 'links', value: '9', platform: 'reach' },
    { text: 'maps', value: '10', platform: 'reach' },
    { text: 'newsletters', value: '11', platform: 'reach' },
    { text: 'notices', value: '12', platform: 'reach' },
    { text: 'parent-directory', value: '13', platform: 'reach' },
    { text: 'subscriptions', value: '14', platform: 'reach' },
    { text: 'timetable', value: '15', platform: 'reach' },
    { text: 'videos', value: '16', platform: 'reach' },
    { text: 'classes', value: '17', platform: 'schoolbox' },
    { text: 'due-work', value: '18', platform: 'schoolbox' },
    { text: 'events', value: '19', platform: 'schoolbox' },
    { text: 'groups', value: '20', platform: 'schoolbox' },
    { text: 'homepage-news', value: '21', platform: 'schoolbox' },
    { text: 'messages', value: '22', platform: 'schoolbox' },
    { text: 'news', value: '23', platform: 'schoolbox' },
    { text: 'timetable', value: '24', platform: 'schoolbox' },
    { text: 'links', value: '25', platform: 'core' },
    { text: 'paperwork-slips', value: '26', platform: 'parent' },
    { text: 'absences', value: '27', platform: 'edumate' },
    { text: 'calendar', value: '28', platform: 'edumate' },
    { text: 'future-events', value: '29', platform: 'edumate' },
    { text: 'future-tasks', value: '30', platform: 'edumate' },
    { text: 'news', value: '31', platform: 'edumate' },
    { text: 'timetable', value: '32', platform: 'edumate' },
    { text: 'todos', value: '33', platform: 'edumate' },
    { text: 'events', value: '34', platform: 'tass' },
    { text: 'excursions', value: '35', platform: 'tass' },
    { text: 'notices', value: '36', platform: 'tass' },
    { text: 'notifications', value: '37', platform: 'tass' },
    { text: 'parents', value: '38', platform: 'tass' },
    { text: 'students', value: '39', platform: 'tass' },
    { text: 'timetable', value: '40', platform: 'tass' },
    { text: 'boarding-boarding', value: '41', platform: 'reach' },
    { text: 'edustack-forms', value: '42', platform: 'reach' }
  ]

  return obj
}
